### ISSUE TITLE
CSS 常用的居中方式

### ISSUE THREAD

**Issue by uniquexiaobai** [uniquexiaobai/blog#5]
CSS常见的居中方式有很多种，这里介绍常见的几种居中方式

[demo](https://codepen.io/uniquexiaobai/pen/NoaYwy?editors=1100)

## 水平居中
1. 利用 flexbox 水平居中
```css
.parent {
    display: flex;
    justify-content: center;
}
```

2. 适用于要水平居中的元素是 block 型，且设定了固定的宽度
```css
.child {
    margin: 0 auto;
}
```
3. 利用 transform 水平居中元素
```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    left: 50%;
    transform: translateX(-50%);
}
```
4. 适用于要水平居中的元素是 inline、inline-block、inline-flex 型，也可以水平居中 container 中的文本
```css
.parent {
    text-align: center;
}
```
5. 利用 css2 的 table 布局水平居中元素
```css
.child {
    display: table;
    margin: 0 auto;
}
```

## 垂直居中
1. 利用 flexbox 布局使元素水平居中
```css
.parent {
    display: flex;
    align-items: center;
}
```
2. 适用于要居中的元素是 block 型，且有固定的高度
```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    top: 50%;
    height: 200px;
    margin-top: -150px;
}
```
3. 适用于要居中的元素是 block 型
```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    top: 50%;
    transform: translateY(-50%)
}
```
4. 利用 css2 table 布局垂直居中元素
```css
.parent {
    display: table-cell;
    vertical-align: middle;
}
```
5. 利用 line-height 垂直居中 box 中的文字
```css
.child {
    height: 20px;
    line-height: 20px;
}
```

## 水平垂直居中
1. 利用 flexbox 使元素水平垂直居中，适用于所有类型的元素
```css
.parent {
    display: flex;
    justify-content: center;
    align-items: center;
}
```
2. 适用于要居中的元素有固定的宽高
```css
.parent {
    position: relative;
}
.child {
    width: 100px;
    height: 40px;
    position: absolute;
    top: 50%;
    left: 50%;
    margin: -20px 0 0 -50px; 
}
```
3. 利用 transform 居中元素
```css
.parent {
    position: relative;
}
.child {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```
4. 利用 css3 的 calc(), 同样需要要居中的元素有固定的宽高
```css
.parent {
    position: relative;
}
.child {
    width: 100px;
    height: 40px;
    position: absolute;
    top: calc(50% - 20px);
    left: calc(50% - 50px);
}
```
5. 适用于要居中的元素有固定的宽高
```css
.parent {
    position: relative;
}
.child {
    width: 100px;
    height: 40px;
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
}
```
6. 利用 css2 的 table 布局水平垂直居中元素
```css
.parent {
    display: table-cell;
    text-align: center;
    vertical-align: middle;
}
```
